version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "backend"
    groups:
      spring-boot:
        patterns:
          - "org.springframework.boot:*"
          - "org.springframework.*"
          - "org.springframework.security:*"
      backend-minor-patch:
        update-types:
          - "minor"
          - "patch"
      backend-majors:
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions:
        patterns:
          - "*"
