-- Baseline estrutural do LumiLivre.
-- Gerado a partir das entidades JPA atuais. Substituir por pg_dump --schema-only
-- do Supabase antes de aplicar em producao, caso o schema real tenha diferencas.

CREATE TABLE IF NOT EXISTS cdd_classificacao (
    codigo VARCHAR(255) PRIMARY KEY,
    descricao VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS curso (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS modulo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS turno (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS genero (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS aluno (
    matricula VARCHAR(5) PRIMARY KEY,
    nome_completo VARCHAR(255) NOT NULL,
    foto VARCHAR(500),
    cpf VARCHAR(11),
    data_nascimento DATE,
    celular VARCHAR(11),
    email VARCHAR(100),
    curso_id INTEGER NOT NULL,
    turno_id INTEGER NOT NULL,
    modulo_id INTEGER NOT NULL,
    cep VARCHAR(8),
    logradouro VARCHAR(255),
    complemento VARCHAR(55),
    bairro VARCHAR(55),
    localidade VARCHAR(55),
    uf VARCHAR(2),
    numero_casa INTEGER,
    penalidade VARCHAR(20),
    penalidade_expira_em TIMESTAMP,
    emprestimos_count INTEGER NOT NULL DEFAULT 0,
    data_inclusao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aluno_curso FOREIGN KEY (curso_id) REFERENCES curso (id),
    CONSTRAINT fk_aluno_turno FOREIGN KEY (turno_id) REFERENCES turno (id),
    CONSTRAINT fk_aluno_modulo FOREIGN KEY (modulo_id) REFERENCES modulo (id)
);

CREATE TABLE IF NOT EXISTS usuario (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    aluno_matricula VARCHAR(5),
    CONSTRAINT fk_usuario_aluno FOREIGN KEY (aluno_matricula) REFERENCES aluno (matricula)
);

CREATE TABLE IF NOT EXISTS livro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    isbn VARCHAR(20) UNIQUE,
    nome VARCHAR(255) NOT NULL,
    data_lancamento DATE,
    numero_paginas INTEGER,
    cdd_codigo VARCHAR(255),
    editora VARCHAR(55) NOT NULL,
    classificacao_etaria VARCHAR(55) NOT NULL,
    edicao VARCHAR(55),
    volume INTEGER,
    quantidade INTEGER,
    sinopse TEXT,
    autor VARCHAR(255),
    tipo_capa VARCHAR(55),
    imagem VARCHAR(5000),
    avaliacao DOUBLE PRECISION DEFAULT 4.6,
    data_inclusao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_livro_cdd FOREIGN KEY (cdd_codigo) REFERENCES cdd_classificacao (codigo)
);

CREATE TABLE IF NOT EXISTS livro_genero (
    livro_id BIGINT NOT NULL,
    genero_id INTEGER NOT NULL,
    PRIMARY KEY (livro_id, genero_id),
    CONSTRAINT fk_livro_genero_livro FOREIGN KEY (livro_id) REFERENCES livro (id),
    CONSTRAINT fk_livro_genero_genero FOREIGN KEY (genero_id) REFERENCES genero (id)
);

CREATE TABLE IF NOT EXISTS exemplar (
    tombo VARCHAR(10) PRIMARY KEY,
    status_livro VARCHAR(55),
    livro_id BIGINT NOT NULL,
    localizacao_fisica VARCHAR(255) NOT NULL,
    data_inclusao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_exemplar_livro FOREIGN KEY (livro_id) REFERENCES livro (id)
);

CREATE TABLE IF NOT EXISTS emprestimo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_emprestimo TIMESTAMP NOT NULL,
    data_devolucao TIMESTAMP NOT NULL,
    penalidade VARCHAR(59),
    status_emprestimo VARCHAR(55),
    aluno_matricula VARCHAR(5) NOT NULL,
    exemplar_tombo VARCHAR(10) NOT NULL,
    CONSTRAINT fk_emprestimo_aluno FOREIGN KEY (aluno_matricula) REFERENCES aluno (matricula),
    CONSTRAINT fk_emprestimo_exemplar FOREIGN KEY (exemplar_tombo) REFERENCES exemplar (tombo)
);

CREATE TABLE IF NOT EXISTS solicitacao_emprestimo (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aluno_matricula VARCHAR(5) NOT NULL,
    exemplar_tombo VARCHAR(10) NOT NULL,
    data_solicitacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDENTE',
    observacao VARCHAR(255),
    CONSTRAINT fk_solicitacao_aluno FOREIGN KEY (aluno_matricula) REFERENCES aluno (matricula),
    CONSTRAINT fk_solicitacao_exemplar FOREIGN KEY (exemplar_tombo) REFERENCES exemplar (tombo)
);

CREATE TABLE IF NOT EXISTS tcc (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    alunos VARCHAR(255) NOT NULL,
    orientadores VARCHAR(255),
    curso_id INTEGER NOT NULL,
    ano_conclusao VARCHAR(255),
    semestre_conclusao VARCHAR(255),
    arquivo_pdf VARCHAR(255),
    foto VARCHAR(255),
    link_externo VARCHAR(255),
    ativo BOOLEAN DEFAULT TRUE,
    CONSTRAINT fk_tcc_curso FOREIGN KEY (curso_id) REFERENCES curso (id)
);

CREATE TABLE IF NOT EXISTS token_reset_senha (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    usuario_id INTEGER NOT NULL,
    data_expiracao TIMESTAMP NOT NULL,
    CONSTRAINT fk_token_reset_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);

CREATE INDEX IF NOT EXISTS idx_aluno_curso ON aluno (curso_id);
CREATE INDEX IF NOT EXISTS idx_aluno_turno ON aluno (turno_id);
CREATE INDEX IF NOT EXISTS idx_aluno_modulo ON aluno (modulo_id);
CREATE INDEX IF NOT EXISTS idx_livro_cdd ON livro (cdd_codigo);
CREATE INDEX IF NOT EXISTS idx_exemplar_livro ON exemplar (livro_id);
CREATE INDEX IF NOT EXISTS idx_emprestimo_aluno ON emprestimo (aluno_matricula);
CREATE INDEX IF NOT EXISTS idx_emprestimo_exemplar ON emprestimo (exemplar_tombo);
CREATE INDEX IF NOT EXISTS idx_emprestimo_status ON emprestimo (status_emprestimo);
CREATE INDEX IF NOT EXISTS idx_solicitacao_aluno ON solicitacao_emprestimo (aluno_matricula);
CREATE INDEX IF NOT EXISTS idx_solicitacao_status ON solicitacao_emprestimo (status);
