-- =============================================================================
--  LumiLivre — DDL standalone (Postgres 13+)
-- -----------------------------------------------------------------------------
--  Script equivalente ao baseline V1..V5 + materialized views V3.
--  Pode ser executado em qualquer instancia PostgreSQL self-hosted, fora do
--  Flyway, para criar o schema do zero. Idempotente: usa IF NOT EXISTS e
--  CREATE OR REPLACE quando possivel.
--
--  Diferencas em relacao a versao Flyway:
--   - Sem `ALTER TABLE ... ENABLE ROW LEVEL SECURITY`. RLS deny-by-default
--     so faz sentido quando a Data API (PostgREST/Supabase) tambem acessa o
--     banco. Em deploy self-hosted onde so o backend acessa, RLS e ruido.
--     Para reativar, descomente a secao 8.
--   - Inclui linhas COMMENT ON ... explicando regras de negocio.
--
--  Encoding esperado: UTF-8. Locale recomendado: pt_BR.UTF-8 ou en_US.UTF-8.
--  Versao Postgres minima: 13 (gen_random_uuid via pgcrypto).
-- =============================================================================

-- ----------------------------------------------------------------------------
-- 1. Extensoes
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;   -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS citext   WITH SCHEMA public;   -- email case-insensitive
CREATE EXTENSION IF NOT EXISTS pg_trgm  WITH SCHEMA public;   -- ILIKE com GIN
CREATE EXTENSION IF NOT EXISTS unaccent WITH SCHEMA public;   -- normalizacao de acentos

CREATE OR REPLACE FUNCTION immutable_unaccent(text) RETURNS text
    LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS
$$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$;

CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- ----------------------------------------------------------------------------
-- 2. Tabelas de referencia
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS course (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(120) NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uq_course_name UNIQUE (name)
);
COMMENT ON TABLE  course IS 'Catalogo de cursos atendidos pela biblioteca.';
COMMENT ON COLUMN course.name IS 'Nome unico do curso (ex.: Desenvolvimento de Sistemas).';

CREATE TABLE IF NOT EXISTS academic_module (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_academic_module PRIMARY KEY (id),
    CONSTRAINT uq_academic_module_name UNIQUE (name)
);
COMMENT ON TABLE academic_module IS 'Modulos / etapas curriculares (Modulo 1..4, Basico, Egresso).';

CREATE TABLE IF NOT EXISTS study_shift (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_study_shift PRIMARY KEY (id),
    CONSTRAINT uq_study_shift_name UNIQUE (name)
);
COMMENT ON TABLE study_shift IS 'Turnos (Matutino, Vespertino, Noturno, Integral).';

CREATE TABLE IF NOT EXISTS genre (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id),
    CONSTRAINT uq_genre_name UNIQUE (name)
);
COMMENT ON TABLE genre IS 'Generos literarios. Regra de negocio limita a 3 generos por livro.';

CREATE TABLE IF NOT EXISTS dewey_classification (
    code        VARCHAR(20)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_dewey_classification PRIMARY KEY (code)
);
COMMENT ON TABLE dewey_classification IS 'Classificacao Decimal de Dewey (CDD). Chave natural por compatibilidade com legados.';

-- ----------------------------------------------------------------------------
-- 3. student
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS student (
    id                     UUID         NOT NULL DEFAULT gen_random_uuid(),
    registration_number    VARCHAR(20)  NOT NULL,
    full_name              VARCHAR(255) NOT NULL,
    avatar_url             VARCHAR(1024),
    cpf                    VARCHAR(11),
    birth_date             DATE,
    phone_number           VARCHAR(20),
    email                  CITEXT,
    course_id              INTEGER      NOT NULL,
    academic_module_id     INTEGER      NOT NULL,
    study_shift_id         INTEGER      NOT NULL,
    postal_code            VARCHAR(8),
    street                 VARCHAR(255),
    address_complement     VARCHAR(55),
    district               VARCHAR(55),
    city                   VARCHAR(55),
    state_code             CHAR(2),
    street_number          INTEGER,
    penalty_code           VARCHAR(20),
    penalty_expires_at     TIMESTAMPTZ,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at             TIMESTAMPTZ,
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT uq_student_registration_number UNIQUE (registration_number),
    CONSTRAINT fk_student_course             FOREIGN KEY (course_id)            REFERENCES course (id)            ON DELETE RESTRICT,
    CONSTRAINT fk_student_academic_module    FOREIGN KEY (academic_module_id)   REFERENCES academic_module (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_student_study_shift        FOREIGN KEY (study_shift_id)       REFERENCES study_shift (id)       ON DELETE RESTRICT,
    CONSTRAINT ck_student_state_code         CHECK (state_code IS NULL OR state_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_student_cpf                CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$')
);
COMMENT ON TABLE student IS 'Aluno catalogado na biblioteca. Soft-delete via deleted_at.';
COMMENT ON COLUMN student.registration_number IS 'Matricula unica. Usada como login e como senha inicial do aluno.';
COMMENT ON COLUMN student.penalty_code IS 'Valores Java: RECORD / WARNING / SUSPENSION / BLOCK / BAN.';
COMMENT ON COLUMN student.penalty_expires_at IS 'Quando > now(), o aluno esta bloqueado para emprestimos.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_cpf
    ON student (cpf)   WHERE cpf   IS NOT NULL AND deleted_at IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_email
    ON student (email) WHERE email IS NOT NULL AND deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_student_touch ON student;
CREATE TRIGGER trg_student_touch BEFORE UPDATE ON student
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 4. app_user
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS app_user (
    id               UUID         NOT NULL DEFAULT gen_random_uuid(),
    email            CITEXT       NOT NULL,
    password_hash    VARCHAR(255),
    role             VARCHAR(30)  NOT NULL,
    student_id       UUID,
    preferred_locale VARCHAR(10)  NOT NULL DEFAULT 'pt-BR',
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email      UNIQUE (email),
    CONSTRAINT uq_app_user_student_id UNIQUE (student_id),
    CONSTRAINT fk_app_user_student    FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE RESTRICT,
    CONSTRAINT ck_app_user_role       CHECK (role IN ('ADMIN', 'LIBRARIAN', 'STUDENT'))
);
COMMENT ON TABLE  app_user IS 'Credenciais e perfil de acesso. 0..1 -> 1 com student quando role = STUDENT.';
COMMENT ON COLUMN app_user.preferred_locale IS 'pt-BR | en-US. Consumido pelo MessageResolver para resolver e-mails.';

DROP TRIGGER IF EXISTS trg_app_user_touch ON app_user;
CREATE TRIGGER trg_app_user_touch BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 5. book, book_genre, book_copy
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS book (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    isbn                VARCHAR(20),
    title               VARCHAR(255) NOT NULL,
    publication_date    DATE,
    page_count          INTEGER,
    dewey_code          VARCHAR(20),
    publisher           VARCHAR(120) NOT NULL,
    age_rating          VARCHAR(30)  NOT NULL,
    edition             VARCHAR(55),
    volume              INTEGER,
    synopsis            TEXT,
    author              VARCHAR(255),
    cover_type          VARCHAR(30),
    cover_url           VARCHAR(1024),
    rating              DOUBLE PRECISION DEFAULT 4.6,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT pk_book PRIMARY KEY (id),
    CONSTRAINT fk_book_dewey FOREIGN KEY (dewey_code) REFERENCES dewey_classification (code) ON DELETE RESTRICT,
    CONSTRAINT ck_book_publication_not_future CHECK (publication_date IS NULL OR publication_date <= CURRENT_DATE),
    CONSTRAINT ck_book_page_count_positive    CHECK (page_count IS NULL OR page_count > 0),
    CONSTRAINT ck_book_rating_range           CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5))
);
COMMENT ON TABLE book IS 'Titulo logico. Exemplares fisicos ficam em book_copy.';

CREATE UNIQUE INDEX IF NOT EXISTS uq_book_isbn
    ON book (isbn) WHERE isbn IS NOT NULL AND deleted_at IS NULL;

DROP TRIGGER IF EXISTS trg_book_touch ON book;
CREATE TRIGGER trg_book_touch BEFORE UPDATE ON book
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS book_genre (
    book_id  UUID    NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT pk_book_genre PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genre_book  FOREIGN KEY (book_id)  REFERENCES book (id)  ON DELETE CASCADE,
    CONSTRAINT fk_book_genre_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_copy (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    copy_code       VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    book_id         UUID         NOT NULL,
    shelf_location  VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT pk_book_copy PRIMARY KEY (id),
    CONSTRAINT uq_book_copy_copy_code UNIQUE (copy_code),
    CONSTRAINT fk_book_copy_book FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT,
    CONSTRAINT ck_book_copy_status CHECK (status IN ('AVAILABLE', 'BORROWED', 'UNAVAILABLE', 'MAINTENANCE'))
);
COMMENT ON TABLE  book_copy IS 'Exemplar fisico identificado por copy_code (tombo).';
COMMENT ON COLUMN book_copy.status IS 'AVAILABLE | BORROWED | UNAVAILABLE | MAINTENANCE.';

DROP TRIGGER IF EXISTS trg_book_copy_touch ON book_copy;
CREATE TRIGGER trg_book_copy_touch BEFORE UPDATE ON book_copy
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 6. loan, loan_request, reservation
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS loan (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    borrowed_at     TIMESTAMPTZ  NOT NULL,
    due_at          TIMESTAMPTZ  NOT NULL,
    returned_at     TIMESTAMPTZ,
    penalty_code    VARCHAR(20),
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    student_id      UUID         NOT NULL,
    book_copy_id    UUID         NOT NULL,
    renewal_count   INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_loan PRIMARY KEY (id),
    CONSTRAINT fk_loan_student   FOREIGN KEY (student_id)   REFERENCES student (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_loan_book_copy FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) ON DELETE RESTRICT,
    CONSTRAINT ck_loan_status             CHECK (status IN ('ACTIVE', 'COMPLETED', 'OVERDUE')),
    CONSTRAINT ck_loan_due_after_borrowed CHECK (due_at >= borrowed_at),
    CONSTRAINT ck_loan_returned_valid     CHECK (returned_at IS NULL OR returned_at >= borrowed_at),
    CONSTRAINT ck_loan_renewal_nonneg     CHECK (renewal_count >= 0)
);
COMMENT ON COLUMN loan.status IS 'ACTIVE | COMPLETED | OVERDUE.';
COMMENT ON COLUMN loan.penalty_code IS 'Penalidade aplicada na devolucao: RECORD / WARNING / SUSPENSION / BLOCK / BAN.';

DROP TRIGGER IF EXISTS trg_loan_touch ON loan;
CREATE TRIGGER trg_loan_touch BEFORE UPDATE ON loan
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS loan_request (
    id             UUID         NOT NULL DEFAULT gen_random_uuid(),
    student_id     UUID         NOT NULL,
    book_copy_id   UUID         NOT NULL,
    requested_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    status         VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    note           VARCHAR(255),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_loan_request PRIMARY KEY (id),
    CONSTRAINT fk_loan_request_student   FOREIGN KEY (student_id)   REFERENCES student (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_loan_request_book_copy FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) ON DELETE RESTRICT,
    CONSTRAINT ck_loan_request_status    CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'))
);

DROP TRIGGER IF EXISTS trg_loan_request_touch ON loan_request;
CREATE TRIGGER trg_loan_request_touch BEFORE UPDATE ON loan_request
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS reservation (
    id              UUID         NOT NULL DEFAULT gen_random_uuid(),
    student_id      UUID         NOT NULL,
    book_id         UUID         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'WAITING',
    queue_position  INTEGER      NOT NULL,
    expires_at      TIMESTAMPTZ,
    notified_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CONSTRAINT fk_reservation_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservation_book    FOREIGN KEY (book_id)    REFERENCES book (id)    ON DELETE RESTRICT,
    CONSTRAINT ck_reservation_status  CHECK (status IN ('WAITING', 'READY', 'CANCELLED', 'EXPIRED', 'FULFILLED')),
    CONSTRAINT ck_reservation_queue_position_positive CHECK (queue_position > 0)
);

DROP TRIGGER IF EXISTS trg_reservation_touch ON reservation;
CREATE TRIGGER trg_reservation_touch BEFORE UPDATE ON reservation
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 7. thesis, password_reset_token, outbox_event, audit_log
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS thesis (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    title               VARCHAR(255) NOT NULL,
    authors             VARCHAR(500) NOT NULL,
    advisors            VARCHAR(500),
    course_id           INTEGER      NOT NULL,
    completion_year     INTEGER,
    completion_semester VARCHAR(10),
    pdf_url             VARCHAR(1024),
    cover_url           VARCHAR(1024),
    external_url        VARCHAR(1024),
    is_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT pk_thesis PRIMARY KEY (id),
    CONSTRAINT fk_thesis_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE RESTRICT,
    CONSTRAINT ck_thesis_year_range CHECK (completion_year IS NULL OR completion_year BETWEEN 1900 AND 2100)
);

DROP TRIGGER IF EXISTS trg_thesis_touch ON thesis;
CREATE TRIGGER trg_thesis_touch BEFORE UPDATE ON thesis
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE IF NOT EXISTS password_reset_token (
    id          BIGINT       GENERATED ALWAYS AS IDENTITY,
    token       VARCHAR(255) NOT NULL,
    app_user_id UUID         NOT NULL,
    expires_at  TIMESTAMPTZ  NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT pk_password_reset_token            PRIMARY KEY (id),
    CONSTRAINT uq_password_reset_token_token      UNIQUE (token),
    CONSTRAINT uq_password_reset_token_app_user   UNIQUE (app_user_id),
    CONSTRAINT fk_password_reset_token_app_user   FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS outbox_event (
    id              BIGINT       GENERATED ALWAYS AS IDENTITY,
    event_type      VARCHAR(30)  NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    subject         VARCHAR(255) NOT NULL,
    body            TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    retry_count     INTEGER      NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,
    next_retry_at   TIMESTAMPTZ,
    CONSTRAINT pk_outbox_event PRIMARY KEY (id),
    CONSTRAINT ck_outbox_event_status       CHECK (status IN ('PENDING', 'SENT', 'FAILED', 'DEAD_LETTER')),
    CONSTRAINT ck_outbox_event_retry_nonneg CHECK (retry_count >= 0)
);
COMMENT ON TABLE outbox_event IS 'Outbox pattern para SMTP. Append-only; publisher agendado consome PENDING.';

CREATE TABLE IF NOT EXISTS audit_log (
    id             BIGINT       GENERATED ALWAYS AS IDENTITY,
    actor          VARCHAR(100) NOT NULL,
    actor_role     VARCHAR(50)  NOT NULL,
    target_id      VARCHAR(200),
    action         VARCHAR(100) NOT NULL,
    result         VARCHAR(20)  NOT NULL,
    error_message  TEXT,
    occurred_at    TIMESTAMPTZ  NOT NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (id),
    CONSTRAINT ck_audit_log_result CHECK (result IN ('SUCCESS', 'FAILURE', 'DENIED'))
);
COMMENT ON TABLE audit_log IS 'Trilha de auditoria administrativa. Append-only; nunca atualize ou apague.';

-- ----------------------------------------------------------------------------
-- 8. (Opcional) Row Level Security deny-by-default
--    Habilite apenas se for expor a Data API publica (Supabase/PostgREST).
--    Em deploy onde so o backend acessa o banco, RLS e overhead sem ganho.
-- ----------------------------------------------------------------------------
-- ALTER TABLE course               ENABLE ROW LEVEL SECURITY; ALTER TABLE course               FORCE ROW LEVEL SECURITY;
-- ALTER TABLE academic_module      ENABLE ROW LEVEL SECURITY; ALTER TABLE academic_module      FORCE ROW LEVEL SECURITY;
-- ALTER TABLE study_shift          ENABLE ROW LEVEL SECURITY; ALTER TABLE study_shift          FORCE ROW LEVEL SECURITY;
-- ALTER TABLE genre                ENABLE ROW LEVEL SECURITY; ALTER TABLE genre                FORCE ROW LEVEL SECURITY;
-- ALTER TABLE dewey_classification ENABLE ROW LEVEL SECURITY; ALTER TABLE dewey_classification FORCE ROW LEVEL SECURITY;
-- ALTER TABLE student              ENABLE ROW LEVEL SECURITY; ALTER TABLE student              FORCE ROW LEVEL SECURITY;
-- ALTER TABLE app_user             ENABLE ROW LEVEL SECURITY; ALTER TABLE app_user             FORCE ROW LEVEL SECURITY;
-- ALTER TABLE book                 ENABLE ROW LEVEL SECURITY; ALTER TABLE book                 FORCE ROW LEVEL SECURITY;
-- ALTER TABLE book_genre           ENABLE ROW LEVEL SECURITY; ALTER TABLE book_genre           FORCE ROW LEVEL SECURITY;
-- ALTER TABLE book_copy            ENABLE ROW LEVEL SECURITY; ALTER TABLE book_copy            FORCE ROW LEVEL SECURITY;
-- ALTER TABLE loan                 ENABLE ROW LEVEL SECURITY; ALTER TABLE loan                 FORCE ROW LEVEL SECURITY;
-- ALTER TABLE loan_request         ENABLE ROW LEVEL SECURITY; ALTER TABLE loan_request         FORCE ROW LEVEL SECURITY;
-- ALTER TABLE reservation          ENABLE ROW LEVEL SECURITY; ALTER TABLE reservation          FORCE ROW LEVEL SECURITY;
-- ALTER TABLE thesis               ENABLE ROW LEVEL SECURITY; ALTER TABLE thesis               FORCE ROW LEVEL SECURITY;
-- ALTER TABLE password_reset_token ENABLE ROW LEVEL SECURITY; ALTER TABLE password_reset_token FORCE ROW LEVEL SECURITY;
-- ALTER TABLE outbox_event         ENABLE ROW LEVEL SECURITY; ALTER TABLE outbox_event         FORCE ROW LEVEL SECURITY;
-- ALTER TABLE audit_log            ENABLE ROW LEVEL SECURITY; ALTER TABLE audit_log            FORCE ROW LEVEL SECURITY;

-- ----------------------------------------------------------------------------
-- 9. Materialized views do dashboard (equivalente a V3)
-- ----------------------------------------------------------------------------
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_dashboard_stats AS
SELECT
    COUNT(*) FILTER (WHERE l.status = 'ACTIVE')    AS active_loans,
    COUNT(*) FILTER (WHERE l.status = 'OVERDUE')   AS overdue_loans,
    COUNT(*) FILTER (WHERE l.status = 'COMPLETED') AS completed_loans,
    COALESCE(AVG(
        EXTRACT(EPOCH FROM (l.returned_at - l.borrowed_at)) / 86400.0
    ) FILTER (WHERE l.status = 'COMPLETED' AND l.returned_at IS NOT NULL), 0) AS avg_return_days,
    (SELECT COUNT(*) FROM loan_request WHERE status = 'PENDING') AS pending_requests,
    (SELECT COUNT(*) FROM reservation  WHERE status = 'WAITING') AS waiting_reservations
FROM loan l
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS mv_dashboard_stats_idx ON mv_dashboard_stats ((1));

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_top_books AS
SELECT
    b.id                                AS book_id,
    b.title                             AS title,
    b.author,
    COALESCE(b.cover_url, '')           AS cover_url,
    COUNT(l.id)                         AS total_loans,
    COALESCE(b.rating, 0)               AS rating
FROM book b
JOIN book_copy bc ON bc.book_id = b.id
JOIN loan l       ON l.book_copy_id = bc.id
WHERE b.deleted_at IS NULL
GROUP BY b.id, b.title, b.author, b.cover_url, b.rating
ORDER BY total_loans DESC
LIMIT 20
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS mv_top_books_idx ON mv_top_books (book_id);

CREATE MATERIALIZED VIEW IF NOT EXISTS mv_loans_by_month AS
SELECT
    DATE_TRUNC('month', l.borrowed_at) AS month,
    COUNT(*)                           AS total
FROM loan l
WHERE l.borrowed_at >= now() - INTERVAL '12 months'
GROUP BY month
ORDER BY month
WITH DATA;

CREATE UNIQUE INDEX IF NOT EXISTS mv_loans_by_month_idx ON mv_loans_by_month (month);

-- ----------------------------------------------------------------------------
-- 10. Indices auxiliares (equivalente a V4 — busca + foreign keys)
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_student_full_name_trgm ON student USING GIN (immutable_unaccent(full_name) gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_book_title_trgm        ON book    USING GIN (immutable_unaccent(title)     gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_book_author_trgm       ON book    USING GIN (immutable_unaccent(author)    gin_trgm_ops);
CREATE INDEX IF NOT EXISTS idx_book_publisher_trgm    ON book    USING GIN (immutable_unaccent(publisher) gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_loan_student_status_due ON loan      (student_id, status, due_at);
CREATE INDEX IF NOT EXISTS idx_book_copy_book_status   ON book_copy (book_id, status);
CREATE INDEX IF NOT EXISTS idx_loan_request_status     ON loan_request (status);
CREATE INDEX IF NOT EXISTS idx_reservation_book_status ON reservation  (book_id, status, queue_position);

CREATE INDEX IF NOT EXISTS idx_outbox_event_status_next ON outbox_event (status, next_retry_at);
CREATE INDEX IF NOT EXISTS idx_audit_log_actor_when     ON audit_log    (actor, occurred_at);

-- ----------------------------------------------------------------------------
-- Fim do script standalone. Para popular dados de referencia em PT-BR
-- (cursos, modulos, turnos, generos, CDD), execute V5__seed_reference_data.sql
-- ou edite conforme o catalogo local.
-- ----------------------------------------------------------------------------
