-- =============================================================================
--  LumiLivre - Baseline V2 (EN)
--  V1__create_core_schema_en.sql
-- -----------------------------------------------------------------------------
--  Schema que substitui o baseline preservado em src/main/resources/db/legacy
-- =============================================================================

-- ----------------------------------------------------------------------------
-- 1. Extensoes
-- ----------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS pgcrypto;       -- gen_random_uuid()
CREATE EXTENSION IF NOT EXISTS citext;         -- emails case-insensitive
CREATE EXTENSION IF NOT EXISTS pg_trgm;        -- ILIKE com GIN
CREATE EXTENSION IF NOT EXISTS unaccent;       -- normalizacao de acentos
-- CREATE EXTENSION IF NOT EXISTS btree_gin;   -- habilitar apenas se medicao justificar

-- Wrapper IMMUTABLE para permitir unaccent em indice expressao.
CREATE OR REPLACE FUNCTION immutable_unaccent(text) RETURNS text
    LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT AS
$$ SELECT unaccent('unaccent', $1) $$;

-- Trigger helper: toca updated_at em cada UPDATE.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger
    LANGUAGE plpgsql AS
$$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- ----------------------------------------------------------------------------
-- 2. Tabelas de referencia (dominio estatico, PK INTEGER)
-- ----------------------------------------------------------------------------
CREATE TABLE course (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(120) NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id),
    CONSTRAINT uq_course_name UNIQUE (name)
);

CREATE TABLE academic_module (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_academic_module PRIMARY KEY (id),
    CONSTRAINT uq_academic_module_name UNIQUE (name)
);

CREATE TABLE study_shift (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(50)  NOT NULL,
    CONSTRAINT pk_study_shift PRIMARY KEY (id),
    CONSTRAINT uq_study_shift_name UNIQUE (name)
);

CREATE TABLE genre (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name       VARCHAR(100) NOT NULL,
    CONSTRAINT pk_genre PRIMARY KEY (id),
    CONSTRAINT uq_genre_name UNIQUE (name)
);

CREATE TABLE dewey_classification (
    code        VARCHAR(20)  NOT NULL,
    description VARCHAR(255),
    CONSTRAINT pk_dewey_classification PRIMARY KEY (code)
);

-- ----------------------------------------------------------------------------
-- 3. student (PK UUID, registration_number vira UNIQUE)
-- ----------------------------------------------------------------------------
CREATE TABLE student (
    id                     UUID        NOT NULL DEFAULT gen_random_uuid(),
    registration_number    VARCHAR(20) NOT NULL,
    full_name              VARCHAR(255) NOT NULL,
    avatar_url             VARCHAR(1024),
    cpf                    VARCHAR(11),
    birth_date             DATE,
    phone_number           VARCHAR(20),
    email                  CITEXT,
    course_id              INTEGER     NOT NULL,
    academic_module_id     INTEGER     NOT NULL,
    study_shift_id         INTEGER     NOT NULL,
    postal_code            VARCHAR(8),
    street                 VARCHAR(255),
    address_complement     VARCHAR(55),
    district               VARCHAR(55),
    city                   VARCHAR(55),
    state_code             CHAR(2),
    street_number          INTEGER,
    penalty_code           VARCHAR(20),
    penalty_expires_at     TIMESTAMPTZ,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at             TIMESTAMPTZ,
    CONSTRAINT pk_student PRIMARY KEY (id),
    CONSTRAINT uq_student_registration_number UNIQUE (registration_number),
    CONSTRAINT fk_student_course            FOREIGN KEY (course_id)            REFERENCES course (id)            ON DELETE RESTRICT,
    CONSTRAINT fk_student_academic_module   FOREIGN KEY (academic_module_id)   REFERENCES academic_module (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_student_study_shift       FOREIGN KEY (study_shift_id)       REFERENCES study_shift (id)       ON DELETE RESTRICT,
    CONSTRAINT ck_student_state_code CHECK (state_code IS NULL OR state_code ~ '^[A-Z]{2}$'),
    CONSTRAINT ck_student_cpf        CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$')
);

-- Unicidades parciais: so quando o valor existe.
CREATE UNIQUE INDEX uq_student_cpf   ON student (cpf)   WHERE cpf   IS NOT NULL AND deleted_at IS NULL;
CREATE UNIQUE INDEX uq_student_email ON student (email) WHERE email IS NOT NULL AND deleted_at IS NULL;

CREATE TRIGGER trg_student_touch BEFORE UPDATE ON student
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 4. app_user (FK opcional para student - papel STUDENT)
-- ----------------------------------------------------------------------------
CREATE TABLE app_user (
    id             UUID        NOT NULL DEFAULT gen_random_uuid(),
    email          CITEXT      NOT NULL,
    password_hash  VARCHAR(255),
    role           VARCHAR(30) NOT NULL,
    student_id     UUID,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,
    CONSTRAINT pk_app_user PRIMARY KEY (id),
    CONSTRAINT uq_app_user_email      UNIQUE (email),
    CONSTRAINT uq_app_user_student_id UNIQUE (student_id),
    CONSTRAINT fk_app_user_student    FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE RESTRICT,
    CONSTRAINT ck_app_user_role       CHECK (role IN ('ADMIN', 'LIBRARIAN', 'STUDENT'))
);

CREATE TRIGGER trg_app_user_touch BEFORE UPDATE ON app_user
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 5. book, book_genre, book_copy
-- ----------------------------------------------------------------------------
CREATE TABLE book (
    id                  UUID         NOT NULL DEFAULT gen_random_uuid(),
    isbn                VARCHAR(20),
    title               VARCHAR(255) NOT NULL,
    publication_date    DATE,
    page_count          INTEGER,
    dewey_code          VARCHAR(20),
    publisher           VARCHAR(120) NOT NULL,
    age_rating          VARCHAR(30)  NOT NULL,
    edition             VARCHAR(55),
    volume              INTEGER,
    synopsis            TEXT,
    author              VARCHAR(255),
    cover_type          VARCHAR(30),
    cover_url           VARCHAR(1024),
    rating              DOUBLE PRECISION DEFAULT 4.6,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT pk_book PRIMARY KEY (id),
    CONSTRAINT fk_book_dewey FOREIGN KEY (dewey_code) REFERENCES dewey_classification (code) ON DELETE RESTRICT,
    CONSTRAINT ck_book_publication_not_future CHECK (publication_date IS NULL OR publication_date <= CURRENT_DATE),
    CONSTRAINT ck_book_page_count_positive    CHECK (page_count IS NULL OR page_count > 0),
    CONSTRAINT ck_book_rating_range           CHECK (rating IS NULL OR (rating >= 0 AND rating <= 5))
);

CREATE UNIQUE INDEX uq_book_isbn ON book (isbn) WHERE isbn IS NOT NULL AND deleted_at IS NULL;

CREATE TRIGGER trg_book_touch BEFORE UPDATE ON book
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE book_genre (
    book_id  UUID    NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT pk_book_genre PRIMARY KEY (book_id, genre_id),
    CONSTRAINT fk_book_genre_book  FOREIGN KEY (book_id)  REFERENCES book (id)  ON DELETE CASCADE,
    CONSTRAINT fk_book_genre_genre FOREIGN KEY (genre_id) REFERENCES genre (id) ON DELETE RESTRICT
);

CREATE TABLE book_copy (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    copy_code       VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    book_id         UUID        NOT NULL,
    shelf_location  VARCHAR(255) NOT NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CONSTRAINT pk_book_copy PRIMARY KEY (id),
    CONSTRAINT uq_book_copy_copy_code UNIQUE (copy_code),
    CONSTRAINT fk_book_copy_book FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE RESTRICT,
    CONSTRAINT ck_book_copy_status CHECK (status IN ('AVAILABLE', 'BORROWED', 'UNAVAILABLE', 'MAINTENANCE'))
);

CREATE TRIGGER trg_book_copy_touch BEFORE UPDATE ON book_copy
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 6. loan, loan_request, reservation
-- ----------------------------------------------------------------------------
CREATE TABLE loan (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    borrowed_at     TIMESTAMPTZ NOT NULL,
    due_at          TIMESTAMPTZ NOT NULL,
    returned_at     TIMESTAMPTZ,
    penalty_code    VARCHAR(20),
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    student_id      UUID        NOT NULL,
    book_copy_id    UUID        NOT NULL,
    renewal_count   INTEGER     NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_loan PRIMARY KEY (id),
    CONSTRAINT fk_loan_student   FOREIGN KEY (student_id)   REFERENCES student (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_loan_book_copy FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) ON DELETE RESTRICT,
    CONSTRAINT ck_loan_status            CHECK (status IN ('ACTIVE', 'COMPLETED', 'OVERDUE')),
    CONSTRAINT ck_loan_due_after_borrowed CHECK (due_at >= borrowed_at),
    CONSTRAINT ck_loan_returned_valid    CHECK (returned_at IS NULL OR returned_at >= borrowed_at),
    CONSTRAINT ck_loan_renewal_nonneg    CHECK (renewal_count >= 0)
);

CREATE TRIGGER trg_loan_touch BEFORE UPDATE ON loan
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE loan_request (
    id             UUID        NOT NULL DEFAULT gen_random_uuid(),
    student_id     UUID        NOT NULL,
    book_copy_id   UUID        NOT NULL,
    requested_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    note           VARCHAR(255),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_loan_request PRIMARY KEY (id),
    CONSTRAINT fk_loan_request_student   FOREIGN KEY (student_id)   REFERENCES student (id)   ON DELETE RESTRICT,
    CONSTRAINT fk_loan_request_book_copy FOREIGN KEY (book_copy_id) REFERENCES book_copy (id) ON DELETE RESTRICT,
    CONSTRAINT ck_loan_request_status    CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED'))
);

CREATE TRIGGER trg_loan_request_touch BEFORE UPDATE ON loan_request
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE reservation (
    id              UUID        NOT NULL DEFAULT gen_random_uuid(),
    student_id      UUID        NOT NULL,
    book_id         UUID        NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'WAITING',
    queue_position  INTEGER     NOT NULL,
    expires_at      TIMESTAMPTZ,
    notified_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_reservation PRIMARY KEY (id),
    CONSTRAINT fk_reservation_student FOREIGN KEY (student_id) REFERENCES student (id) ON DELETE RESTRICT,
    CONSTRAINT fk_reservation_book    FOREIGN KEY (book_id)    REFERENCES book (id)    ON DELETE RESTRICT,
    CONSTRAINT ck_reservation_status  CHECK (status IN ('WAITING', 'READY', 'CANCELLED', 'EXPIRED', 'FULFILLED')),
    CONSTRAINT ck_reservation_queue_position_positive CHECK (queue_position > 0)
);

CREATE TRIGGER trg_reservation_touch BEFORE UPDATE ON reservation
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- ----------------------------------------------------------------------------
-- 7. thesis, password_reset_token
-- ----------------------------------------------------------------------------
CREATE TABLE thesis (
    id                  UUID        NOT NULL DEFAULT gen_random_uuid(),
    title               VARCHAR(255) NOT NULL,
    authors             VARCHAR(500) NOT NULL,
    advisors            VARCHAR(500),
    course_id           INTEGER     NOT NULL,
    completion_year     INTEGER,
    completion_semester VARCHAR(10),
    pdf_url             VARCHAR(1024),
    cover_url           VARCHAR(1024),
    external_url        VARCHAR(1024),
    is_active           BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at          TIMESTAMPTZ,
    CONSTRAINT pk_thesis PRIMARY KEY (id),
    CONSTRAINT fk_thesis_course FOREIGN KEY (course_id) REFERENCES course (id) ON DELETE RESTRICT,
    CONSTRAINT ck_thesis_year_range CHECK (completion_year IS NULL OR completion_year BETWEEN 1900 AND 2100)
);

CREATE TRIGGER trg_thesis_touch BEFORE UPDATE ON thesis
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

CREATE TABLE password_reset_token (
    id          BIGINT      GENERATED ALWAYS AS IDENTITY,
    token       VARCHAR(255) NOT NULL,
    app_user_id UUID         NOT NULL,
    expires_at  TIMESTAMPTZ NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pk_password_reset_token            PRIMARY KEY (id),
    CONSTRAINT uq_password_reset_token_token      UNIQUE (token),
    CONSTRAINT uq_password_reset_token_app_user   UNIQUE (app_user_id),
    CONSTRAINT fk_password_reset_token_app_user   FOREIGN KEY (app_user_id) REFERENCES app_user (id) ON DELETE CASCADE
);

-- ----------------------------------------------------------------------------
-- 8. RLS deny-by-default (ADR-005)
--    Backend conecta como owner/postgres e bypassa; Data API fica bloqueada.
-- ----------------------------------------------------------------------------
ALTER TABLE course                 ENABLE ROW LEVEL SECURITY; ALTER TABLE course                 FORCE ROW LEVEL SECURITY;
ALTER TABLE academic_module        ENABLE ROW LEVEL SECURITY; ALTER TABLE academic_module        FORCE ROW LEVEL SECURITY;
ALTER TABLE study_shift            ENABLE ROW LEVEL SECURITY; ALTER TABLE study_shift            FORCE ROW LEVEL SECURITY;
ALTER TABLE genre                  ENABLE ROW LEVEL SECURITY; ALTER TABLE genre                  FORCE ROW LEVEL SECURITY;
ALTER TABLE dewey_classification   ENABLE ROW LEVEL SECURITY; ALTER TABLE dewey_classification   FORCE ROW LEVEL SECURITY;
ALTER TABLE student                ENABLE ROW LEVEL SECURITY; ALTER TABLE student                FORCE ROW LEVEL SECURITY;
ALTER TABLE app_user               ENABLE ROW LEVEL SECURITY; ALTER TABLE app_user               FORCE ROW LEVEL SECURITY;
ALTER TABLE book                   ENABLE ROW LEVEL SECURITY; ALTER TABLE book                   FORCE ROW LEVEL SECURITY;
ALTER TABLE book_genre             ENABLE ROW LEVEL SECURITY; ALTER TABLE book_genre             FORCE ROW LEVEL SECURITY;
ALTER TABLE book_copy              ENABLE ROW LEVEL SECURITY; ALTER TABLE book_copy              FORCE ROW LEVEL SECURITY;
ALTER TABLE loan                   ENABLE ROW LEVEL SECURITY; ALTER TABLE loan                   FORCE ROW LEVEL SECURITY;
ALTER TABLE loan_request           ENABLE ROW LEVEL SECURITY; ALTER TABLE loan_request           FORCE ROW LEVEL SECURITY;
ALTER TABLE reservation            ENABLE ROW LEVEL SECURITY; ALTER TABLE reservation            FORCE ROW LEVEL SECURITY;
ALTER TABLE thesis                 ENABLE ROW LEVEL SECURITY; ALTER TABLE thesis                 FORCE ROW LEVEL SECURITY;
ALTER TABLE password_reset_token   ENABLE ROW LEVEL SECURITY; ALTER TABLE password_reset_token   FORCE ROW LEVEL SECURITY;
