CREATE TABLE IF NOT EXISTS outbox_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(30) NOT NULL,
    recipient_email VARCHAR(255) NOT NULL,
    subject VARCHAR(255) NOT NULL,
    body TEXT NOT NULL,
    status VARCHAR(10) NOT NULL DEFAULT 'PENDING',
    retry_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    next_retry_at TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_outbox_event_status_created_at
    ON outbox_event (status, created_at);

CREATE INDEX IF NOT EXISTS idx_outbox_event_status_retry_count
    ON outbox_event (status, retry_count);
