-- =============================================================================
--  V5__seed_reference_data.sql
-- -----------------------------------------------------------------------------
--  Dados de referencia do dominio (PT-BR por natureza do negocio).
--  Idempotente via ON CONFLICT. Nao contem dados de negocio (emprestimos,
--  alunos, livros) - esses ficam no seed demo opt-in em db/seed.
-- =============================================================================

DO $$
DECLARE
    seed_table text;
BEGIN
    FOREACH seed_table IN ARRAY ARRAY[
        'course',
        'academic_module',
        'study_shift',
        'genre',
        'dewey_classification'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I DISABLE ROW LEVEL SECURITY', seed_table);
    END LOOP;
END $$;

-- ----------------------------------------------------------------------------
-- course
-- ----------------------------------------------------------------------------
INSERT INTO course (name) VALUES
    ('Administração'),
    ('Desenvolvimento de Sistemas'),
    ('Logística'),
    ('Recursos Humanos'),
    ('Seguranca do Trabalho'),
    ('Técnico em Enfermagem'),
    ('Técnico em Contabilidade'),
    ('Técnico em Mecatrônica')
ON CONFLICT (name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- academic_module
-- ----------------------------------------------------------------------------
INSERT INTO academic_module (name) VALUES
    ('Módulo 1'),
    ('Módulo 2'),
    ('Módulo 3'),
    ('Módulo 4'),
    ('Básico'),
    ('Egresso')
ON CONFLICT (name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- study_shift
-- ----------------------------------------------------------------------------
INSERT INTO study_shift (name) VALUES
    ('Matutino'),
    ('Vespertino'),
    ('Noturno'),
    ('Integral')
ON CONFLICT (name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- genre
-- ----------------------------------------------------------------------------
INSERT INTO genre (name) VALUES
    ('Romance'),
    ('Ficção Científica'),
    ('Fantasia'),
    ('História'),
    ('Biografia'),
    ('Tecnologia'),
    ('Administração'),
    ('Saúde'),
    ('Educação'),
    ('Didático'),
    ('Infantojuvenil'),
    ('Suspense'),
    ('Poesia'),
    ('Quadrinhos'),
    ('Autoajuda'),
    ('Clássicos')
ON CONFLICT (name) DO NOTHING;

-- ----------------------------------------------------------------------------
-- dewey_classification (resumo das classes principais da CDD)
--   Detalhamento completo pode ser carregado depois via importacao.
-- ----------------------------------------------------------------------------
INSERT INTO dewey_classification (code, description) VALUES
    ('000', 'Generalidades, Ciência da Computação e Informação'),
    ('001', 'Conhecimento'),
    ('002', 'O livro (escrita, bibliotecas e tópicos relacionados)'),
    ('003', 'Sistemas'),
    ('004', 'Processamento de dados e Ciência da Computação'),
    ('005', 'Programação, programas e dados de computador'),
    ('006', 'Métodos especiais de computação (ex: IA, multimídia, RV)'),
    ('007', 'Não atribuído'),
    ('008', 'Não atribuído'),
    ('009', 'Não atribuído'),
    ('010', 'Bibliografias'),
    ('011', 'Bibliografias'),
    ('012', 'Bibliografias de indivíduos'),
    ('013', 'Não atribuído'),
    ('014', 'Bibliografias de obras anônimas e pseudônimas'),
    ('015', 'Bibliografias de obras de locais específicos'),
    ('016', 'Bibliografias de obras sobre assuntos específicos'),
    ('017', 'Catálogos gerais de assuntos'),
    ('018', 'Catálogos organizados por autor, data, etc. [movido para 017]'),
    ('019', 'Catálogos dicionários [movido para 017]'),
    ('020', 'Biblioteconomia e ciência da informação'),
    ('021', 'Relações de bibliotecas (com arquivos, centros de informação, etc.)'),
    ('022', 'Administração de planta física'),
    ('023', 'Gestão de pessoal'),
    ('024', 'Não atribuído'),
    ('025', 'Operações de biblioteca'),
    ('026', 'Bibliotecas para assuntos específicos'),
    ('027', 'Bibliotecas gerais'),
    ('028', 'Leitura e uso de outras mídias de informação'),
    ('029', 'Não atribuído'),
    ('030', 'Obras enciclopédicas gerais'),
    ('031', 'Enciclopédias em inglês americano'),
    ('032', 'Enciclopédias em inglês'),
    ('033', 'Enciclopédias em outras línguas germânicas'),
    ('034', 'Enciclopédias em francês, occitano e catalão'),
    ('035', 'Enciclopédias em italiano, romeno e línguas relacionadas'),
    ('036', 'Enciclopédias em espanhol e português'),
    ('037', 'Enciclopédias em línguas eslavas'),
    ('038', 'Enciclopédias em línguas escandinavas'),
    ('039', 'Enciclopédias em outras línguas'),
    ('040', 'Não atribuído — anteriormente Biografias'),
    ('050', 'Publicações em série gerais'),
    ('051', 'Periódicos em inglês americano'),
    ('052', 'Periódicos em inglês'),
    ('053', 'Periódicos em outras línguas germânicas'),
    ('054', 'Periódicos em francês, occitano e catalão'),
    ('055', 'Periódicos em italiano, romeno e línguas relacionadas'),
    ('056', 'Periódicos em espanhol e português'),
    ('057', 'Periódicos em línguas eslavas'),
    ('058', 'Periódicos em línguas escandinavas'),
    ('059', 'Periódicos em outras línguas'),
    ('060', 'Organizações gerais e museologia'),
    ('061', 'Organizações na América do Norte'),
    ('062', 'Organizações nas Ilhas Britânicas; na Inglaterra'),
    ('063', 'Organizações na Europa Central; na Alemanha'),
    ('064', 'Organizações na França e Mônaco'),
    ('065', 'Organizações na Itália e ilhas adjacentes'),
    ('066', 'Organizações na Península Ibérica e ilhas adjacentes'),
    ('067', 'Organizações na Europa Oriental; na Rússia'),
    ('068', 'Organizações em outras áreas geográficas'),
    ('069', 'Museologia'),
    ('070', 'Mídia de notícias, jornalismo e publicação'),
    ('071', 'Jornais na América do Norte'),
    ('072', 'Jornais nas Ilhas Britânicas; na Inglaterra'),
    ('073', 'Jornais na Europa Central; na Alemanha'),
    ('074', 'Jornais na França e Mônaco'),
    ('075', 'Jornais na Itália e ilhas adjacentes'),
    ('076', 'Jornais na Península Ibérica e ilhas adjacentes'),
    ('077', 'Jornais na Europa Oriental; na Rússia'),
    ('078', 'Jornais na Escandinávia'),
    ('079', 'Jornais em outras áreas geográficas'),
    ('080', 'Coleções gerais de citações'),
    ('081', 'Coleções em inglês americano'),
    ('082', 'Coleções em inglês'),
    ('083', 'Coleções em outras línguas germânicas'),
    ('084', 'Coleções em francês, occitano, catalão'),
    ('085', 'Coleções em italiano, romeno e línguas relacionadas'),
    ('086', 'Coleções em espanhol e português'),
    ('087', 'Coleções em línguas eslavas'),
    ('088', 'Coleções em línguas escandinavas'),
    ('089', 'Coleções em outras línguas'),
    ('090', 'Manuscritos e livros raros'),
    ('091', 'Manuscritos'),
    ('092', 'Livros xilográficos'),
    ('093', 'Incunábulos'),
    ('094', 'Livros impressos'),
    ('095', 'Livros notáveis pelas encadernações'),
    ('096', 'Livros notáveis pelas ilustrações'),
    ('097', 'Livros notáveis pela propriedade ou origem'),
    ('098', 'Obras proibidas, falsificações e fraudes'),
    ('099', 'Livros notáveis pelo formato'),
    ('100', 'Filosofia e Psicologia'),
    ('101', 'Teoria da filosofia'),
    ('102', 'Miscelânea'),
    ('103', 'Dicionários e enciclopédias'),
    ('104', 'Não mais utilizado — anteriormente Ensaios'),
    ('105', 'Publicações em série'),
    ('106', 'Organizações e gestão'),
    ('107', 'Educação, pesquisa, tópicos relacionados à filosofia'),
    ('108', 'Grupos de pessoas'),
    ('109', 'História e biografia coletada'),
    ('110', 'Metafísica'),
    ('111', 'Ontologia'),
    ('112', 'Não mais utilizado — anteriormente Metodologia'),
    ('113', 'Cosmologia (Filosofia da natureza)'),
    ('114', 'Espaço'),
    ('115', 'Tempo'),
    ('116', 'Mudança'),
    ('117', 'Estrutura'),
    ('118', 'Força e energia'),
    ('119', 'Número e quantidade'),
    ('120', 'Epistemologia, causalidade e humanidade'),
    ('121', 'Epistemologia (teoria do conhecimento)'),
    ('122', 'Causalidade'),
    ('123', 'Determinismo e indeterminismo'),
    ('124', 'Teleologia'),
    ('125', 'Não mais utilizado — anteriormente Infinito'),
    ('126', 'O eu'),
    ('127', 'O inconsciente e o subconsciente'),
    ('128', 'Humanidade'),
    ('129', 'Origem e destino das almas individuais'),
    ('130', 'Parapsicologia e ocultismo'),
    ('131', 'Métodos parapsicológicos e ocultos para alcançar bem-estar, felicidade, sucesso'),
    ('132', 'Não mais utilizado — anteriormente Transtornos mentais'),
    ('133', 'Tópicos específicos em parapsicologia e ocultismo'),
    ('134', 'Não mais utilizado — anteriormente Mesmerismo e clarividência'),
    ('135', 'Sonhos e mistérios'),
    ('136', 'Não mais utilizado — anteriormente Características mentais'),
    ('137', 'Grafologia adivinhatória'),
    ('138', 'Fisiognomia'),
    ('139', 'Frenologia'),
    ('140', 'Escolas filosóficas e pontos de vista específicos'),
    ('141', 'Idealismo e sistemas e doutrinas relacionadas'),
    ('142', 'Filosofia crítica'),
    ('143', 'Bergsonismo e intuicionismo'),
    ('144', 'Humanismo e sistemas e doutrinas relacionadas'),
    ('145', 'Sensacionismo'),
    ('146', 'Naturalismo e sistemas e doutrinas relacionadas'),
    ('147', 'Panteísmo e sistemas e doutrinas relacionadas'),
    ('148', 'Dogmatismo, ecletismo, liberalismo, sincretismo e tradicionalismo'),
    ('149', 'Outros sistemas e doutrinas filosóficas'),
    ('150', 'Psicologia'),
    ('151', 'Não mais utilizado — anteriormente Intelecto'),
    ('152', 'Percepção sensorial, movimento, emoções e impulsos fisiológicos'),
    ('153', 'Processos mentais conscientes e inteligência'),
    ('154', 'Estados e processos subconscientes e alterados'),
    ('155', 'Psicologia diferencial e do desenvolvimento'),
    ('156', 'Psicologia comparada'),
    ('157', 'Não mais utilizado — anteriormente Emoções'),
    ('158', 'Psicologia aplicada'),
    ('159', 'Não mais utilizado — anteriormente Vontade'),
    ('160', 'Lógica filosófica'),
    ('161', 'Indução'),
    ('162', 'Dedução'),
    ('163', 'Não atribuído ou não mais utilizado'),
    ('164', 'Não atribuído ou não mais utilizado'),
    ('165', 'Falácias e fontes de erro'),
    ('166', 'Silogismos'),
    ('167', 'Hipóteses'),
    ('168', 'Argumento e persuasão'),
    ('169', 'Analogia'),
    ('170', 'Ética (filosofia moral)'),
    ('171', 'Sistemas éticos'),
    ('172', 'Ética política'),
    ('173', 'Ética das relações familiares'),
    ('174', 'Ética ocupacional'),
    ('175', 'Ética da recreação, lazer, apresentações públicas, comunicação'),
    ('176', 'Ética do sexo e reprodução'),
    ('177', 'Ética das relações sociais'),
    ('178', 'Ética do consumo'),
    ('179', 'Outras normas éticas'),
    ('180', 'Filosofia antiga, medieval, oriental'),
    ('181', 'Filosofia oriental'),
    ('182', 'Filosofias gregas pré-socráticas'),
    ('183', 'Filosofias sofística, socrática e relacionadas'),
    ('184', 'Filosofia platônica'),
    ('185', 'Filosofia aristotélica'),
    ('186', 'Filosofias cética e neoplatônica'),
    ('187', 'Filosofia epicurista'),
    ('188', 'Filosofia estoica'),
    ('189', 'Filosofia ocidental medieval'),
    ('190', 'Filosofia ocidental moderna e outras não orientais'),
    ('191', 'Filosofia dos Estados Unidos e Canadá'),
    ('192', 'Filosofia das Ilhas Britânicas'),
    ('193', 'Filosofia da Alemanha e Áustria'),
    ('194', 'Filosofia da França'),
    ('195', 'Filosofia da Itália'),
    ('196', 'Filosofia da Espanha e Portugal'),
    ('197', 'Filosofia da Rússia'),
    ('198', 'Filosofia da Escandinávia e Finlândia'),
    ('199', 'Filosofia em outras áreas geográficas'),
    ('200', 'Religião'),
    ('201', 'Mitologia religiosa, classes gerais, relações inter-religiosas, teologia social'),
    ('202', 'Doutrinas'),
    ('203', 'Culto público e outras práticas'),
    ('204', 'Experiência religiosa, vida, prática'),
    ('205', 'Ética religiosa'),
    ('206', 'Líderes e organização'),
    ('207', 'Missões e educação religiosa'),
    ('208', 'Fontes'),
    ('209', 'Seitas e movimentos de reforma'),
    ('210', 'Filosofia e teoria da religião'),
    ('211', 'Conceitos de Deus'),
    ('212', 'Existência, formas de conhecer a Deus, atributos de Deus'),
    ('213', 'Criação'),
    ('214', 'Teodiceia'),
    ('215', 'Ciência e religião'),
    ('216', 'Não mais utilizado — anteriormente Mal'),
    ('217', 'Não mais utilizado — anteriormente Oração'),
    ('218', 'Humanidade'),
    ('219', 'Não mais utilizado — anteriormente Analogias'),
    ('220', 'A Bíblia'),
    ('221', 'Antigo Testamento (Tanakh)'),
    ('222', 'Livros históricos do Antigo Testamento'),
    ('223', 'Livros poéticos do Antigo Testamento'),
    ('224', 'Livros proféticos do Antigo Testamento'),
    ('225', 'Novo Testamento'),
    ('226', 'Evangelhos e Atos'),
    ('227', 'Epístolas'),
    ('228', 'Apocalipse (Revelação)'),
    ('229', 'Apócrifos, pseudoepígrafos e obras intertestamentárias'),
    ('230', 'Cristianismo'),
    ('231', 'Deus'),
    ('232', 'Jesus Cristo e sua família'),
    ('233', 'Humanidade'),
    ('234', 'Salvação e graça'),
    ('235', 'Seres espirituais'),
    ('236', 'Escatologia'),
    ('237', 'Não mais utilizado — anteriormente Estado futuro'),
    ('238', 'Credos, confissões de fé, alianças e catecismos'),
    ('239', 'Apologética e polêmicas'),
    ('240', 'Teologia moral e devocional cristã'),
    ('241', 'Ética cristã'),
    ('242', 'Literatura devocional'),
    ('243', 'Escritos evangelísticos para indivíduos e famílias'),
    ('244', 'Não mais utilizado — anteriormente Ficção religiosa'),
    ('245', 'Não mais utilizado — anteriormente Hinologia'),
    ('246', 'Uso da arte no Cristianismo'),
    ('247', 'Mobiliário de igreja e artigos relacionados'),
    ('248', 'Experiência, prática e vida cristã'),
    ('249', 'Observâncias cristãs na vida familiar'),
    ('250', 'Igreja cristã local e ordens religiosas cristãs'),
    ('251', 'Pregação (Homilética)'),
    ('252', 'Textos de sermões'),
    ('253', 'Ofício e trabalho pastoral (Teologia pastoral)'),
    ('254', 'Administração paroquial'),
    ('255', 'Congregações e ordens religiosas'),
    ('256', 'Não mais utilizado — anteriormente Sociedades religiosas'),
    ('257', 'Não mais utilizado — anteriormente Escolas paroquiais, bibliotecas, etc.'),
    ('258', 'Não mais utilizado — anteriormente Medicina paroquial'),
    ('259', 'Cuidado pastoral de famílias, de grupos específicos de pessoas'),
    ('260', 'Teologia social e eclesiástica cristã'),
    ('261', 'Teologia social e relações e atitudes inter-religiosas'),
    ('262', 'Eclesiologia'),
    ('263', 'Dias, épocas, locais de observância religiosa'),
    ('264', 'Culto público'),
    ('265', 'Sacramentos, outros ritos e atos'),
    ('266', 'Missões'),
    ('267', 'Associações para o trabalho religioso'),
    ('268', 'Educação religiosa'),
    ('269', 'Renovação espiritual'),
    ('270', 'História, tratamento geográfico, biografia do Cristianismo'),
    ('271', 'Congregações e ordens religiosas na história da igreja'),
    ('272', 'Perseguições na história da igreja'),
    ('273', 'Controvérsias doutrinárias e heresias na história geral da igreja'),
    ('274', 'Cristianismo na Europa'),
    ('275', 'Cristianismo na Ásia'),
    ('276', 'Cristianismo na África'),
    ('277', 'Cristianismo na América do Norte'),
    ('278', 'Cristianismo na América do Sul'),
    ('279', 'História do Cristianismo em outras áreas'),
    ('280', 'Denominações e seitas da igreja cristã'),
    ('281', 'Igreja primitiva e igrejas orientais'),
    ('282', 'Igreja Católica Romana'),
    ('283', 'Igrejas Anglicanas'),
    ('284', 'Denominações protestantes de origem continental (Luterana, Reformada Continental)'),
    ('285', 'Igrejas Presbiterianas, Igrejas Reformadas centradas na América, Igrejas Congregacionais'),
    ('286', 'Igrejas Batistas, Movimento de Restauração, Adventistas'),
    ('287', 'Igrejas Metodistas; igrejas relacionadas ao Metodismo'),
    ('288', 'Não mais utilizado — anteriormente Unitarismo'),
    ('289', 'Outras denominações e seitas'),
    ('290', 'Outras religiões'),
    ('291', 'Não mais utilizado — anteriormente Religião comparada'),
    ('292', 'Religião clássica (Religião grega e romana)'),
    ('293', 'Religião germânica'),
    ('294', 'Religiões de origem índica'),
    ('295', 'Zoroastrismo (Mazdaísmo, Parsismo)'),
    ('296', 'Judaísmo'),
    ('297', 'Islã, Babismo e Fé Bahá''í'),
    ('298', 'Não mais utilizado — anteriormente Mormonismo'),
    ('299', 'Religiões não previstas em outro lugar'),
    ('300', 'Ciências Sociais'),
    ('301', 'Sociologia e antropologia'),
    ('302', 'Interação social'),
    ('303', 'Processos sociais'),
    ('304', 'Fatores que afetam o comportamento social'),
    ('305', 'Grupos de pessoas'),
    ('306', 'Cultura e instituições'),
    ('307', 'Comunidades'),
    ('308', 'Não mais utilizado — anteriormente Poligrafia'),
    ('309', 'Não mais utilizado — anteriormente História da sociologia'),
    ('310', 'Coleções de estatísticas gerais'),
    ('311', 'Não mais utilizado — anteriormente Teoria e métodos'),
    ('312', 'Não mais utilizado — anteriormente População'),
    ('313', 'Não mais utilizado — anteriormente Tópicos especiais'),
    ('314', 'Estatísticas gerais da Europa'),
    ('315', 'Estatísticas gerais da Ásia'),
    ('316', 'Estatísticas gerais da África'),
    ('317', 'Estatísticas gerais da América do Norte'),
    ('318', 'Estatísticas gerais da América do Sul'),
    ('319', 'Estatísticas gerais da Australásia, ilhas do Pacífico, Atlântico, Ártico, Antártida'),
    ('320', 'Ciência política (política e governo)'),
    ('321', 'Sistemas de governos e estados'),
    ('322', 'Relação do estado com grupos organizados e seus membros'),
    ('323', 'Direitos civis e políticos'),
    ('324', 'Processo político'),
    ('325', 'Migração internacional e colonização'),
    ('326', 'Escravidão e emancipação'),
    ('327', 'Relações internacionais'),
    ('328', 'O processo legislativo'),
    ('329', 'Não mais utilizado — anteriormente Partidos políticos'),
    ('330', 'Economia'),
    ('331', 'Economia do trabalho'),
    ('332', 'Economia financeira'),
    ('333', 'Economia da terra e energia'),
    ('334', 'Cooperativas'),
    ('335', 'Socialismo e sistemas relacionados'),
    ('336', 'Finanças públicas'),
    ('337', 'Economia internacional'),
    ('338', 'Produção'),
    ('339', 'Macroeconomia e tópicos relacionados'),
    ('340', 'Direito'),
    ('341', 'Direito das nações'),
    ('342', 'Direito constitucional e administrativo'),
    ('343', 'Direito militar, defesa, propriedade pública, finanças públicas, tributário, comercial, industrial'),
    ('344', 'Direito do trabalho, serviço social, educação, cultural'),
    ('345', 'Direito penal'),
    ('346', 'Direito privado'),
    ('347', 'Processo e tribunais'),
    ('348', 'Leis, regulamentos, casos'),
    ('349', 'Direito de jurisdições específicas, áreas, organizações intergovernamentais regionais'),
    ('350', 'Administração pública e ciência militar'),
    ('351', 'Administração pública'),
    ('352', 'Considerações gerais de administração pública'),
    ('353', 'Campos específicos da administração pública'),
    ('354', 'Administração pública da economia e meio ambiente'),
    ('355', 'Ciência militar'),
    ('356', 'Forças a pé e guerra'),
    ('357', 'Forças montadas e guerra'),
    ('358', 'Forças aéreas e especializadas; engenharia e serviços relacionados'),
    ('359', 'Forças marítimas e guerra'),
    ('360', 'Problemas sociais e serviços; associações'),
    ('361', 'Problemas sociais e serviços sociais'),
    ('362', 'Problemas sociais de e serviços para grupos de pessoas'),
    ('363', 'Outros problemas sociais e serviços'),
    ('364', 'Criminologia'),
    ('365', 'Instituições penais e relacionadas'),
    ('366', 'Associações e sociedades secretas'),
    ('367', 'Clubes gerais'),
    ('368', 'Seguros'),
    ('369', 'Associações'),
    ('370', 'Educação'),
    ('371', 'Escolas e suas atividades, educação especial'),
    ('372', 'Ensino fundamental (educação primária)'),
    ('373', 'Ensino médio (educação secundária)'),
    ('374', 'Educação de adultos'),
    ('375', 'Currículo'),
    ('376', 'Não mais utilizado — anteriormente Educação de mulheres'),
    ('377', 'Não mais utilizado — anteriormente Educação ética'),
    ('378', 'Ensino superior (educação terciária)'),
    ('379', 'Questões de políticas públicas em educação'),
    ('380', 'Comércio, comunicações, transporte'),
    ('381', 'Comércio'),
    ('382', 'Comércio internacional (comércio exterior)'),
    ('383', 'Comunicação postal'),
    ('384', 'Comunicações'),
    ('385', 'Transporte ferroviário'),
    ('386', 'Transporte por via navegável interior e balsa'),
    ('387', 'Transporte aquático, aéreo, espacial'),
    ('388', 'Transporte'),
    ('389', 'Metrologia e padronização'),
    ('390', 'Costumes, etiqueta, folclore'),
    ('391', 'Trajes e aparência pessoal'),
    ('392', 'Costumes do ciclo de vida e da vida doméstica'),
    ('393', 'Costumes fúnebres'),
    ('394', 'Costumes gerais'),
    ('395', 'Etiqueta (boas maneiras)'),
    ('396', 'Não mais utilizado — anteriormente Posição e tratamento das mulheres'),
    ('397', 'Não mais utilizado — anteriormente Estudos de párias'),
    ('398', 'Folclore'),
    ('399', 'Costumes de guerra e diplomacia'),
    ('400', 'Linguagem'),
    ('401', 'Filosofia e teoria, línguas internacionais'),
    ('402', 'Miscelânea'),
    ('403', 'Dicionários, enciclopédias, concordâncias'),
    ('404', 'Tópicos especiais de linguagem'),
    ('405', 'Publicações em série'),
    ('406', 'Organizações e gestão'),
    ('407', 'Educação, pesquisa, tópicos relacionados'),
    ('408', 'Grupos de pessoas'),
    ('409', 'Tratamento geográfico e biografia'),
    ('410', 'Linguística'),
    ('411', 'Sistemas de escrita de formas padrão de línguas'),
    ('412', 'Etimologia de formas padrão de línguas'),
    ('413', 'Dicionários de formas padrão de línguas'),
    ('414', 'Fonologia e fonética de formas padrão de línguas'),
    ('415', 'Gramática de formas padrão de línguas'),
    ('416', 'Não mais utilizado — anteriormente Prosódia'),
    ('417', 'Dialetologia e linguística histórica'),
    ('418', 'Uso padrão (Linguística prescritiva)'),
    ('419', 'Línguas de sinais'),
    ('420', 'Inglês e inglês antigo (Anglo-Saxão)'),
    ('421', 'Sistema de escrita, fonologia, fonética do inglês padrão'),
    ('422', 'Etimologia do inglês padrão'),
    ('423', 'Dicionários do inglês padrão'),
    ('424', 'Não mais utilizado — anteriormente Tesauros de inglês'),
    ('425', 'Gramática do inglês padrão'),
    ('426', 'Não mais utilizado — anteriormente Prosódias inglesas'),
    ('427', 'Variações históricas e geográficas, variações não geográficas modernas do inglês'),
    ('428', 'Uso do inglês padrão (Linguística prescritiva)'),
    ('429', 'Inglês antigo (Anglo-Saxão)'),
    ('430', 'Alemão e línguas relacionadas'),
    ('431', 'Sistemas de escrita, fonologia, fonética do alemão padrão'),
    ('432', 'Etimologia do alemão padrão'),
    ('433', 'Dicionários do alemão padrão'),
    ('434', 'Não atribuído ou não mais utilizado'),
    ('435', 'Gramática do alemão padrão'),
    ('436', 'Não atribuído ou não mais utilizado'),
    ('437', 'Variações históricas e geográficas, variações não geográficas modernas do alemão'),
    ('438', 'Uso do alemão padrão (Linguística prescritiva)'),
    ('439', 'Outras línguas germânicas'),
    ('440', 'Francês e línguas românicas relacionadas'),
    ('441', 'Sistemas de escrita, fonologia, fonética do francês padrão'),
    ('442', 'Etimologia do francês padrão'),
    ('443', 'Dicionários do francês padrão'),
    ('444', 'Não atribuído ou não mais utilizado'),
    ('445', 'Gramática do francês padrão'),
    ('446', 'Não atribuído ou não mais utilizado'),
    ('447', 'Variações históricas e geográficas, variações não geográficas modernas do francês'),
    ('448', 'Uso do francês padrão (Linguística prescritiva)'),
    ('449', 'Occitano, catalão, franco-provençal'),
    ('450', 'Italiano, dálmata, romeno, rético, sardo, corso'),
    ('451', 'Sistemas de escrita, fonologia, fonética do italiano padrão'),
    ('452', 'Etimologia do italiano padrão'),
    ('453', 'Dicionários do italiano padrão'),
    ('454', 'Não atribuído ou não mais utilizado'),
    ('455', 'Gramática do italiano padrão'),
    ('456', 'Não atribuído ou não mais utilizado'),
    ('457', 'Variações históricas e geográficas, variações não geográficas modernas do italiano'),
    ('458', 'Uso do italiano padrão (Linguística prescritiva)'),
    ('459', 'Romeno, rético, sardo, corso'),
    ('460', 'Espanhol, português, galego'),
    ('461', 'Sistemas de escrita, fonologia, fonética do espanhol padrão'),
    ('462', 'Etimologia do espanhol padrão'),
    ('463', 'Dicionários do espanhol padrão'),
    ('464', 'Não atribuído ou não mais utilizado'),
    ('465', 'Gramática do espanhol padrão'),
    ('466', 'Não atribuído ou não mais utilizado'),
    ('467', 'Variações históricas e geográficas, variações não geográficas modernas do espanhol'),
    ('468', 'Uso do espanhol padrão (Linguística prescritiva)'),
    ('469', 'Português'),
    ('470', 'Latim e línguas itálicas relacionadas'),
    ('471', 'Sistemas de escrita, fonologia, fonética do latim clássico'),
    ('472', 'Etimologia do latim clássico'),
    ('473', 'Dicionários do latim clássico'),
    ('474', 'Não atribuído ou não mais utilizado'),
    ('475', 'Gramática do latim clássico'),
    ('476', 'Não atribuído ou não mais utilizado'),
    ('477', 'Latim antigo, pós-clássico, vulgar'),
    ('478', 'Uso do latim clássico (Linguística prescritiva)'),
    ('479', 'Outras línguas itálicas'),
    ('480', 'Grego clássico e línguas helênicas relacionadas'),
    ('481', 'Sistemas de escrita, fonologia, fonética do grego clássico'),
    ('482', 'Etimologia do grego clássico'),
    ('483', 'Dicionários do grego clássico'),
    ('484', 'Não atribuído ou não mais utilizado'),
    ('485', 'Gramática do grego clássico'),
    ('486', 'Não atribuído ou não mais utilizado'),
    ('487', 'Grego pré-clássico e pós-clássico'),
    ('488', 'Uso do grego clássico (Linguística prescritiva)'),
    ('489', 'Outras línguas helênicas'),
    ('490', 'Outras línguas'),
    ('491', 'Línguas indo-europeias orientais e celtas'),
    ('492', 'Línguas afro-asiáticas'),
    ('493', 'Línguas afro-asiáticas não semíticas'),
    ('494', 'Línguas altaicas, urálicas, hiperbóreas, dravidianas, línguas diversas do sul da Ásia'),
    ('495', 'Línguas do Leste Asiático e Sudeste Asiático'),
    ('496', 'Línguas africanas'),
    ('497', 'Línguas nativas norte-americanas'),
    ('498', 'Línguas nativas sul-americanas'),
    ('499', 'Línguas não austronésias da Oceania, línguas austronésias, línguas diversas'),
    ('500', 'Ciências Naturais e Matemática'),
    ('501', 'Filosofia e teoria'),
    ('502', 'Miscelânea'),
    ('503', 'Dicionários, enciclopédias, concordâncias'),
    ('504', 'Não atribuído ou não mais utilizado'),
    ('505', 'Publicações em série'),
    ('506', 'Organizações e gestão'),
    ('507', 'Educação, pesquisa, tópicos relacionados'),
    ('508', 'História natural'),
    ('509', 'História, tratamento geográfico, biografia'),
    ('510', 'Matemática'),
    ('511', 'Princípios gerais de matemática'),
    ('512', 'Álgebra'),
    ('513', 'Aritmética'),
    ('514', 'Topologia'),
    ('515', 'Análise'),
    ('516', 'Geometria'),
    ('517', 'Não atribuído ou não mais utilizado'),
    ('518', 'Análise numérica'),
    ('519', 'Probabilidades e matemática aplicada'),
    ('520', 'Astronomia e ciências afins'),
    ('521', 'Mecânica celeste'),
    ('522', 'Técnicas, procedimentos, aparelhos, equipamentos, materiais'),
    ('523', 'Corpos e fenômenos celestes específicos'),
    ('524', 'Não atribuído ou não mais utilizado'),
    ('525', 'Terra (Geografia astronômica)'),
    ('526', 'Geografia matemática'),
    ('527', 'Navegação celeste'),
    ('528', 'Efemérides'),
    ('529', 'Cronologia'),
    ('530', 'Física'),
    ('531', 'Mecânica clássica'),
    ('532', 'Mecânica dos fluidos'),
    ('533', 'Pneumática (Mecânica dos gases)'),
    ('534', 'Som e vibrações relacionadas'),
    ('535', 'Luz e radiação relacionada'),
    ('536', 'Calor'),
    ('537', 'Eletricidade e eletrônica'),
    ('538', 'Magnetismo'),
    ('539', 'Física moderna'),
    ('540', 'Química e ciências afins'),
    ('541', 'Físico-química'),
    ('542', 'Técnicas, procedimentos, aparelhos, equipamentos, materiais'),
    ('543', 'Química analítica'),
    ('544', 'Não mais utilizado — anteriormente Análise qualitativa'),
    ('545', 'Não mais utilizado — anteriormente Análise quantitativa'),
    ('546', 'Química inorgânica'),
    ('547', 'Química orgânica'),
    ('548', 'Cristalografia'),
    ('549', 'Mineralogia'),
    ('550', 'Ciências da Terra'),
    ('551', 'Geologia, hidrologia, meteorologia'),
    ('552', 'Petrologia'),
    ('553', 'Geologia econômica'),
    ('554', 'Ciências da Terra da Europa'),
    ('555', 'Ciências da Terra da Ásia'),
    ('556', 'Ciências da Terra da África'),
    ('557', 'Ciências da Terra da América do Norte'),
    ('558', 'Ciências da Terra da América do Sul'),
    ('559', 'Ciências da Terra da Australásia, ilhas do Pacífico, Atlântico, Ártico, Antártida, extraterrestres'),
    ('560', 'Paleontologia'),
    ('561', 'Paleobotânica, microrganismos fósseis'),
    ('562', 'Invertebrados fósseis'),
    ('563', 'Diversos invertebrados marinhos e de beira-mar fósseis'),
    ('564', 'Mollusca e Molluscoidea fósseis'),
    ('565', 'Arthropoda fósseis'),
    ('566', 'Chordata fósseis'),
    ('567', 'Vertebrados de sangue frio fósseis'),
    ('568', 'Aves fósseis'),
    ('569', 'Mamíferos fósseis (Mammalia)'),
    ('570', 'Biologia'),
    ('571', 'Fisiologia e assuntos relacionados'),
    ('572', 'Bioquímica'),
    ('573', 'Sistemas fisiológicos específicos em animais, histologia regional e fisiologia em animais'),
    ('574', 'Não atribuído ou não mais utilizado'),
    ('575', 'Partes específicas e sistemas fisiológicos em plantas'),
    ('576', 'Genética e evolução'),
    ('577', 'Ecologia'),
    ('578', 'História natural de organismos e assuntos relacionados'),
    ('579', 'História natural de microrganismos, fungos, algas'),
    ('580', 'Plantas'),
    ('581', 'Tópicos específicos em história natural de plantas'),
    ('582', 'Plantas notáveis por características vegetativas específicas e flores'),
    ('583', 'Magnoliopsida (Dicotiledôneas)'),
    ('584', 'Liliopsida (Monocotiledôneas)'),
    ('585', 'Pinophyta (Gimnospermas)'),
    ('586', 'Cryptogamia (plantas sem sementes)'),
    ('587', 'Pteridophyta'),
    ('588', 'Bryophyta'),
    ('589', 'Não mais utilizado — anteriormente Silvicultura'),
    ('590', 'Animais'),
    ('591', 'Tópicos específicos em história natural de animais'),
    ('592', 'Invertebrados'),
    ('593', 'Diversos invertebrados marinhos e de beira-mar'),
    ('594', 'Mollusca e Molluscoidea'),
    ('595', 'Arthropoda'),
    ('596', 'Chordata'),
    ('597', 'Vertebrados de sangue frio'),
    ('598', 'Aves'),
    ('599', 'Mammalia (mamíferos)'),
    ('600', 'Tecnologia (Ciências Aplicadas)'),
    ('601', 'Filosofia e teoria'),
    ('602', 'Miscelânea'),
    ('603', 'Dicionários, enciclopédias, concordâncias'),
    ('604', 'Desenho técnico, tecnologia de materiais perigosos; grupos de pessoas'),
    ('605', 'Publicações em série'),
    ('606', 'Organizações'),
    ('607', 'Educação, pesquisa, tópicos relacionados'),
    ('608', 'Patentes'),
    ('609', 'História, tratamento geográfico, biografia'),
    ('610', 'Medicina e Saúde'),
    ('611', 'Anatomia humana, citologia, histologia'),
    ('612', 'Fisiologia humana'),
    ('613', 'Saúde e segurança pessoal'),
    ('614', 'Medicina legal; incidência de lesões, feridas, doenças; medicina preventiva pública'),
    ('615', 'Farmacologia e terapêutica'),
    ('616', 'Doenças'),
    ('617', 'Cirurgia, medicina regional, odontologia, oftalmologia, otologia, audiologia'),
    ('618', 'Ginecologia, obstetrícia, pediatria, geriatria'),
    ('619', 'Não mais utilizado — anteriormente Medicina experimental'),
    ('620', 'Engenharia e operações aplicadas'),
    ('621', 'Física aplicada'),
    ('622', 'Mineração e operações relacionadas'),
    ('623', 'Engenharia militar e náutica'),
    ('624', 'Engenharia civil'),
    ('625', 'Engenharia de ferrovias, estradas'),
    ('626', 'Não atribuído ou não mais utilizado'),
    ('627', 'Engenharia hidráulica'),
    ('628', 'Engenharia sanitária'),
    ('629', 'Outros ramos da engenharia'),
    ('630', 'Agricultura e tecnologias relacionadas'),
    ('631', 'Técnicas específicas; aparelhos, equipamentos, materiais'),
    ('632', 'Lesões em plantas, doenças, pragas'),
    ('633', 'Culturas de campo e plantação'),
    ('634', 'Pomares, frutas, silvicultura'),
    ('635', 'Culturas de jardim (horticultura)'),
    ('636', 'Criação de animais'),
    ('637', 'Processamento de laticínios e produtos relacionados'),
    ('638', 'Cultivo de insetos'),
    ('639', 'Caça, pesca, conservação, tecnologias relacionadas'),
    ('640', 'Gestão doméstica e familiar'),
    ('641', 'Alimentos e bebidas'),
    ('642', 'Refeições e serviço de mesa'),
    ('643', 'Habitação e equipamentos domésticos'),
    ('644', 'Utilidades domésticas'),
    ('645', 'Mobiliário doméstico'),
    ('646', 'Costura, roupas, gestão da vida pessoal e familiar'),
    ('647', 'Gestão de residências públicas (economia doméstica institucional)'),
    ('648', 'Limpeza doméstica'),
    ('649', 'Criação de filhos; cuidados domiciliares a pessoas com deficiência e doentes'),
    ('650', 'Administração e serviços auxiliares'),
    ('651', 'Serviços de escritório'),
    ('652', 'Processos de comunicação escrita'),
    ('653', 'Taquigrafia'),
    ('654', 'Não atribuído ou não mais utilizado'),
    ('655', 'Não atribuído ou não mais utilizado'),
    ('656', 'Não atribuído ou não mais utilizado'),
    ('657', 'Contabilidade'),
    ('658', 'Administração geral'),
    ('659', 'Publicidade e relações públicas'),
    ('660', 'Engenharia química e tecnologias relacionadas'),
    ('661', 'Tecnologia de produtos químicos industriais'),
    ('662', 'Tecnologia de explosivos, combustíveis, produtos relacionados'),
    ('663', 'Tecnologia de bebidas'),
    ('664', 'Tecnologia de alimentos'),
    ('665', 'Tecnologia de óleos industriais, gorduras, ceras, gases'),
    ('666', 'Tecnologias cerâmicas e afins'),
    ('667', 'Limpeza, cores, revestimentos, tecnologias relacionadas'),
    ('668', 'Tecnologia de outros produtos orgânicos'),
    ('669', 'Metalurgia'),
    ('670', 'Manufatura'),
    ('671', 'Processos de metalurgia e produtos metálicos primários'),
    ('672', 'Ferro, aço, outras ligas de ferro'),
    ('673', 'Metais não ferrosos'),
    ('674', 'Processamento de madeira, produtos de madeira, cortiça'),
    ('675', 'Processamento de couro e peles'),
    ('676', 'Tecnologia de celulose e papel'),
    ('677', 'Têxteis'),
    ('678', 'Elastômeros e produtos de elastômero'),
    ('679', 'Outros produtos de tipos específicos de materiais'),
    ('680', 'Manufatura de produtos para usos específicos'),
    ('681', 'Instrumentos de precisão e outros dispositivos'),
    ('682', 'Pequenos trabalhos de forja (ferraria)'),
    ('683', 'Ferragens e eletrodomésticos'),
    ('684', 'Móveis e oficinas domésticas'),
    ('685', 'Artigos de couro e pele, e produtos relacionados'),
    ('686', 'Impressão e atividades relacionadas'),
    ('687', 'Roupas e acessórios'),
    ('688', 'Outros produtos finais e tecnologia de embalagem'),
    ('689', 'Não atribuído ou não mais utilizado'),
    ('690', 'Construção de edifícios'),
    ('691', 'Materiais de construção'),
    ('692', 'Práticas auxiliares de construção'),
    ('693', 'Construção em tipos específicos de materiais e para fins específicos'),
    ('694', 'Construção em madeira'),
    ('695', 'Cobertura de telhados'),
    ('696', 'Utilidades'),
    ('697', 'Engenharia de aquecimento, ventilação, ar-condicionado'),
    ('698', 'Acabamento detalhado'),
    ('699', 'Não atribuído ou não mais utilizado'),
    ('700', 'Artes e Recreação'),
    ('701', 'Filosofia e teoria das artes plásticas e decorativas'),
    ('702', 'Miscelânea de artes plásticas e decorativas'),
    ('703', 'Dicionários, enciclopédias, concordâncias de artes plásticas e decorativas'),
    ('704', 'Tópicos especiais em artes plásticas e decorativas'),
    ('705', 'Publicações em série de artes plásticas e decorativas'),
    ('706', 'Organizações e gestão de artes plásticas e decorativas'),
    ('707', 'Educação, pesquisa, tópicos relacionados de artes plásticas e decorativas'),
    ('708', 'Galerias, museus, coleções privadas de artes plásticas e decorativas'),
    ('709', 'História, tratamento geográfico, biografia'),
    ('710', 'Planejamento de área e arquitetura paisagística'),
    ('711', 'Planejamento de área (arte cívica)'),
    ('712', 'Arquitetura paisagística (Design paisagístico)'),
    ('713', 'Arquitetura paisagística de vias de tráfego'),
    ('714', 'Elementos aquáticos na arquitetura paisagística'),
    ('715', 'Plantas lenhosas na arquitetura paisagística'),
    ('716', 'Plantas herbáceas na arquitetura paisagística'),
    ('717', 'Estruturas na arquitetura paisagística'),
    ('718', 'Design paisagístico de cemitérios'),
    ('719', 'Paisagens naturais'),
    ('720', 'Arquitetura'),
    ('721', 'Materiais arquitetônicos e elementos estruturais'),
    ('722', 'Arquitetura desde os primeiros tempos até c. 300'),
    ('723', 'Arquitetura de c. 300 a 1399'),
    ('724', 'Arquitetura de 1400 em diante'),
    ('725', 'Estruturas públicas'),
    ('726', 'Edifícios para fins religiosos e relacionados'),
    ('727', 'Edifícios para fins educacionais e de pesquisa'),
    ('728', 'Edifícios residenciais e relacionados'),
    ('729', 'Design e decoração de estruturas e acessórios'),
    ('730', 'Escultura e artes relacionadas'),
    ('731', 'Processos, formas, temas de escultura'),
    ('732', 'Escultura desde os primeiros tempos até c. 500, escultura de povos não letrados'),
    ('733', 'Escultura grega, etrusca, romana'),
    ('734', 'Escultura de c. 500 a 1399'),
    ('735', 'Escultura de 1400 em diante'),
    ('736', 'Entalhe e entalhes'),
    ('737', 'Numismática e sigilografia'),
    ('738', 'Artes cerâmicas'),
    ('739', 'Trabalho em metal artístico'),
    ('740', 'Artes gráficas'),
    ('741', 'Desenho e desenhos'),
    ('742', 'Perspectiva em desenho'),
    ('743', 'Desenho e desenhos por assunto'),
    ('744', 'Design de comunicação e design visual (proposto)'),
    ('745', 'Artes decorativas'),
    ('746', 'Artes têxteis'),
    ('747', 'Decoração de interiores'),
    ('748', 'Vidro'),
    ('749', 'Móveis e acessórios'),
    ('750', 'Pintura e pinturas'),
    ('751', 'Técnicas, procedimentos, aparelhos, equipamentos, materiais, formas'),
    ('752', 'Cor'),
    ('753', 'Simbolismo, alegoria, mitologia, lenda'),
    ('754', 'Pinturas de gênero'),
    ('755', 'Religião'),
    ('756', 'Não atribuído ou não mais utilizado'),
    ('757', 'Figuras humanas'),
    ('758', 'Natureza, assuntos arquitetônicos e paisagens urbanas, outros assuntos específicos'),
    ('759', 'História, tratamento geográfico, biografia'),
    ('760', 'Gravura e impressões'),
    ('761', 'Processos em relevo (impressão em bloco)'),
    ('762', 'Não atribuído ou não mais utilizado'),
    ('763', 'Processos litográficos (processos planográficos)'),
    ('764', 'Cromolitografia e serigrafia'),
    ('765', 'Gravação em metal'),
    ('766', 'Meio-tom, água-tinta e processos relacionados'),
    ('767', 'Água-forte e ponta-seca'),
    ('768', 'Não atribuído ou não mais utilizado'),
    ('769', 'Impressões'),
    ('770', 'Fotografia, arte computacional, cinematografia, videografia'),
    ('771', 'Técnicas, procedimentos, aparelhos, equipamentos, materiais'),
    ('772', 'Processos de sal metálico'),
    ('773', 'Processos de pigmento de impressão'),
    ('774', 'Não mais utilizado — anteriormente Holografia'),
    ('775', 'Não mais utilizado — anteriormente Fotografia digital'),
    ('776', 'Arte computacional (arte digital)'),
    ('777', 'Cinematografia e videografia'),
    ('778', 'Campos específicos e tipos especiais de fotografia'),
    ('779', 'Imagens fotográficas'),
    ('780', 'Música'),
    ('781', 'Princípios gerais e formas musicais'),
    ('782', 'Música vocal'),
    ('783', 'Música para vozes únicas'),
    ('784', 'Instrumentos e conjuntos instrumentais e sua música'),
    ('785', 'Conjuntos com apenas um instrumento por parte'),
    ('786', 'Instrumentos de teclado, mecânicos, eletrofônicos, percussão'),
    ('787', 'Instrumentos de corda (cordofones)'),
    ('788', 'Instrumentos de sopro (aerofones)'),
    ('789', 'Não atribuído ou não mais utilizado'),
    ('790', 'Artes recreativas e artes cênicas'),
    ('791', 'Apresentações públicas'),
    ('792', 'Apresentações de palco'),
    ('793', 'Jogos e diversões internas'),
    ('794', 'Jogos internos de habilidade'),
    ('795', 'Jogos de azar'),
    ('796', 'Esportes atléticos e ao ar livre e jogos'),
    ('797', 'Esportes aquáticos e esportes aéreos'),
    ('798', 'Esportes equestres e corrida de animais'),
    ('799', 'Pesca, caça, tiro'),
    ('800', 'Literatura'),
    ('801', 'Filosofia e teoria'),
    ('802', 'Miscelânea'),
    ('803', 'Dicionários, enciclopédias, concordâncias'),
    ('804', 'Não atribuído ou não mais utilizado'),
    ('805', 'Publicações em série'),
    ('806', 'Organizações e gestão'),
    ('807', 'Educação, pesquisa, tópicos relacionados'),
    ('808', 'Retórica e coleções de textos literários de mais de duas literaturas'),
    ('809', 'História, descrição, avaliação crítica de mais de duas literaturas'),
    ('810', 'Literatura americana em inglês'),
    ('811', 'Poesia americana em inglês'),
    ('812', 'Drama americano em inglês'),
    ('813', 'Ficção americana em inglês'),
    ('814', 'Ensaios americanos em inglês'),
    ('815', 'Discursos americanos em inglês'),
    ('816', 'Cartas americanas em inglês'),
    ('817', 'Humor e sátira americana em inglês'),
    ('818', 'Escritos diversos americanos em inglês'),
    ('819', 'Não mais utilizado — anteriormente Atividades de quebra-cabeça'),
    ('820', 'Literaturas em inglês e inglês antigo (Anglo-Saxão)'),
    ('821', 'Poesia inglesa'),
    ('822', 'Drama inglês'),
    ('823', 'Ficção inglesa'),
    ('824', 'Ensaios ingleses'),
    ('825', 'Discursos ingleses'),
    ('826', 'Cartas inglesas'),
    ('827', 'Humor e sátira inglesa'),
    ('828', 'Escritos diversos ingleses'),
    ('829', 'Literatura em inglês antigo (Anglo-Saxão)'),
    ('830', 'Literatura alemã e literaturas de línguas relacionadas'),
    ('831', 'Poesia alemã'),
    ('832', 'Drama alemão'),
    ('833', 'Ficção alemã'),
    ('834', 'Ensaios alemães'),
    ('835', 'Discursos alemães'),
    ('836', 'Cartas alemãs'),
    ('837', 'Humor e sátira alemã'),
    ('838', 'Escritos diversos alemães'),
    ('839', 'Outras literaturas germânicas'),
    ('840', 'Literatura francesa e literaturas de línguas românicas relacionadas'),
    ('841', 'Poesia francesa'),
    ('842', 'Drama francês'),
    ('843', 'Ficção francesa'),
    ('844', 'Ensaios franceses'),
    ('845', 'Discursos franceses'),
    ('846', 'Cartas francesas'),
    ('847', 'Humor e sátira francesa'),
    ('848', 'Escritos diversos franceses'),
    ('849', 'Literaturas em occitano, catalão, franco-provençal'),
    ('850', 'Literaturas das línguas italiana, dálmata, romena, rética, sarda, corsa'),
    ('851', 'Poesia italiana'),
    ('852', 'Drama italiano'),
    ('853', 'Ficção italiana'),
    ('854', 'Ensaios italianos'),
    ('855', 'Discursos italianos'),
    ('856', 'Cartas italianas'),
    ('857', 'Humor e sátira italiana'),
    ('858', 'Escritos diversos italianos'),
    ('859', 'Literaturas das línguas romena, rética, sarda, corsa'),
    ('860', 'Literaturas das línguas espanhola, portuguesa, galega'),
    ('861', 'Poesia espanhola'),
    ('862', 'Drama espanhol'),
    ('863', 'Ficção espanhola'),
    ('864', 'Ensaios espanhóis'),
    ('865', 'Discursos espanhóis'),
    ('866', 'Cartas espanholas'),
    ('867', 'Humor e sátira espanhola'),
    ('868', 'Escritos diversos espanhóis'),
    ('869', 'Literaturas portuguesa e brasileira'),
    ('870', 'Literatura latina e literaturas de línguas itálicas relacionadas'),
    ('871', 'Poesia latina'),
    ('872', 'Poesia dramática e drama latino'),
    ('873', 'Poesia épica e ficção latina'),
    ('874', 'Poesia lírica latina'),
    ('875', 'Discursos latinos'),
    ('876', 'Cartas latinas'),
    ('877', 'Humor e sátira latina'),
    ('878', 'Escritos diversos latinos'),
    ('879', 'Literaturas de outras línguas itálicas'),
    ('880', 'Literatura grega clássica e literaturas de línguas helênicas relacionadas'),
    ('881', 'Poesia grega clássica'),
    ('882', 'Drama grego clássico'),
    ('883', 'Poesia épica e ficção grega clássica'),
    ('884', 'Poesia lírica grega clássica'),
    ('885', 'Discursos gregos clássicos'),
    ('886', 'Cartas gregas clássicas'),
    ('887', 'Humor e sátira grega clássica'),
    ('888', 'Escritos diversos gregos clássicos'),
    ('889', 'Literatura grega moderna'),
    ('890', 'Literaturas de outras línguas e famílias de línguas específicas'),
    ('891', 'Literaturas indo-europeias orientais e celtas'),
    ('892', 'Literaturas afro-asiáticas'),
    ('893', 'Literaturas afro-asiáticas não semíticas'),
    ('894', 'Literaturas das línguas altaicas, urálicas, hiperbóreas, dravidianas; literaturas de línguas diversas do sul da Ásia'),
    ('895', 'Literaturas do Leste e Sudeste Asiático'),
    ('896', 'Literaturas africanas'),
    ('897', 'Literaturas de línguas nativas norte-americanas'),
    ('898', 'Literaturas de línguas nativas sul-americanas'),
    ('899', 'Literaturas de línguas não austronésias da Oceania, de línguas austronésias, de línguas diversas'),
    ('900', 'Geografia, História e Biografia'),
    ('901', 'Filosofia e teoria da história'),
    ('902', 'Miscelânea de história'),
    ('903', 'Dicionários, enciclopédias, concordâncias de história'),
    ('904', 'Relatos coletados de eventos'),
    ('905', 'Publicações em série de história'),
    ('906', 'Organizações e gestão de história'),
    ('907', 'Educação, pesquisa, tópicos relacionados de história'),
    ('908', 'História com relação a grupos de pessoas'),
    ('909', 'História mundial'),
    ('910', 'Geografia e viagens'),
    ('911', 'Geografia histórica'),
    ('912', 'Representações gráficas da superfície da Terra e de mundos extraterrestres'),
    ('913', 'Geografia e viagens no mundo antigo'),
    ('914', 'Geografia e viagens na Europa'),
    ('915', 'Geografia e viagens na Ásia'),
    ('916', 'Geografia e viagens na África'),
    ('917', 'Geografia e viagens na América do Norte'),
    ('918', 'Geografia e viagens na América do Sul'),
    ('919', 'Geografia e viagens na Australásia, ilhas do Pacífico, Atlântico, Ártico, Antártida, e mundos extraterrestres'),
    ('920', 'Biografia, genealogia, insígnias'),
    ('921', 'Localização opcional para biografias'),
    ('922', 'Localização opcional para biografias'),
    ('923', 'Localização opcional para biografias'),
    ('924', 'Localização opcional para biografias'),
    ('925', 'Localização opcional para biografias'),
    ('926', 'Localização opcional para biografias'),
    ('927', 'Localização opcional para biografias'),
    ('928', 'Localização opcional para biografias'),
    ('929', 'Genealogia, nomes, insígnias'),
    ('930', 'História do mundo antigo até c. 499'),
    ('931', 'China até 420'),
    ('932', 'Egito até 640'),
    ('933', 'Palestina até 70'),
    ('934', 'Sul da Ásia até 647'),
    ('935', 'Mesopotâmia e Planalto Iraniano até 637'),
    ('936', 'Europa ao norte e oeste da Península Itálica até c. 499'),
    ('937', 'Itália e territórios adjacentes até 476'),
    ('938', 'Grécia até 323'),
    ('939', 'Outras partes do mundo antigo'),
    ('940', 'História da Europa'),
    ('941', 'Ilhas Britânicas'),
    ('942', 'Inglaterra e País de Gales'),
    ('943', 'Alemanha e países vizinhos da Europa Central'),
    ('944', 'França e Mônaco'),
    ('945', 'Itália, San Marino, Cidade do Vaticano, Malta'),
    ('946', 'Espanha, Andorra, Gibraltar, Portugal'),
    ('947', 'Rússia e países vizinhos da Europa Oriental'),
    ('948', 'Escandinávia'),
    ('949', 'Outras partes da Europa'),
    ('950', 'História da Ásia'),
    ('951', 'China e áreas adjacentes'),
    ('952', 'Japão'),
    ('953', 'Península Arábica e áreas adjacentes'),
    ('954', 'Índia e países vizinhos do sul da Ásia'),
    ('955', 'Irã'),
    ('956', 'Oriente Médio (Oriente Próximo)'),
    ('957', 'Sibéria (Rússia Asiática)'),
    ('958', 'Ásia Central'),
    ('959', 'Sudeste Asiático'),
    ('960', 'História da África'),
    ('961', 'Tunísia e Líbia'),
    ('962', 'Egito, Sudão, Sudão do Sul'),
    ('963', 'Etiópia e Eritreia'),
    ('964', 'Marrocos, Ceuta, Melilha, Saara Ocidental, Ilhas Canárias'),
    ('965', 'Argélia'),
    ('966', 'África Ocidental e ilhas costeiras'),
    ('967', 'África Central e ilhas costeiras'),
    ('968', 'África do Sul e África meridional'),
    ('969', 'Ilhas do sul do Oceano Índico'),
    ('970', 'História da América do Norte'),
    ('971', 'Canadá'),
    ('972', 'México, América Central, Índias Ocidentais, Bermudas'),
    ('973', 'Estados Unidos'),
    ('974', 'Nordeste dos Estados Unidos (Nova Inglaterra e estados do Meio-Atlântico)'),
    ('975', 'Sudeste dos Estados Unidos (estados do Atlântico Sul)'),
    ('976', 'Centro-Sul dos Estados Unidos'),
    ('977', 'Centro-Norte dos Estados Unidos'),
    ('978', 'Oeste dos Estados Unidos'),
    ('979', 'Grande Bacia e região da Encosta do Pacífico dos Estados Unidos'),
    ('980', 'História da América do Sul'),
    ('981', 'Brasil'),
    ('982', 'Argentina'),
    ('983', 'Chile'),
    ('984', 'Bolívia'),
    ('985', 'Peru'),
    ('986', 'Colômbia e Equador'),
    ('987', 'Venezuela'),
    ('988', 'Guiana'),
    ('989', 'Paraguai e Uruguai'),
    ('990', 'História da Australásia, ilhas do Pacífico, Atlântico, Ártico, Antártida, mundos extraterrestres'),
    ('991', 'Não atribuído ou não mais utilizado'),
    ('992', 'Não atribuído ou não mais utilizado'),
    ('993', 'Nova Zelândia'),
    ('994', 'Austrália'),
    ('995', 'Nova Guiné e países vizinhos da Melanésia'),
    ('996', 'Polinésia e outras ilhas do Oceano Pacífico'),
    ('997', 'Ilhas do Oceano Atlântico'),
    ('998', 'Ilhas do Ártico e Antártida'),
    ('999', 'Mundos extraterrestres')
ON CONFLICT (code) DO NOTHING;

DO $$
DECLARE
    seed_table text;
BEGIN
    FOREACH seed_table IN ARRAY ARRAY[
        'course',
        'academic_module',
        'study_shift',
        'genre',
        'dewey_classification'
    ]
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', seed_table);
        EXECUTE format('ALTER TABLE %I FORCE ROW LEVEL SECURITY', seed_table);
    END LOOP;
END $$;
